services:
  kafka:
    image: apache/kafka:latest
    container_name: order-kafka
    ports:
      - "9092:9092"docker exec order-kafka /opt/kafka/bin/kafka-topics.sh --create --topic order-events --bootstrap-server localhost:9092 --partitions 3 --replication-factor 1